### ISSUE TITLE
Clean unused branches

### ISSUE THREAD

**Issue by Mr-Precise** [dotdevelop/dotdevelop#103]
In the **403** branches  repository, out of the required 3 - 4 (main, develop, may be backup etc), this creates inconvenience and confusion + because of this, it takes a long time to copy the repository (git clone).
Correct me if I'm wrong

**Comment by lextm** [comment]
But you don't need a full clone to get started, right?

**Comment by gluckez** [comment]
@Mr-Precise when cloning a repository, git does indeed download all branches. but they are designated as remote-tracking branches, so at any time, there is only one main working branch. This does not significantly increase the time to clone a repository, as it doesn't download the full history for each branch.
It is, however, recommended to create your own fork if you like to contribute, and make pull requests towards the main working branch. regardless of the amount of branches, git keeps a history of all commits. So the amount of branches itself is negligent in the face of that.

**Comment by Mr-Precise** [comment]
I will fork the repository and try to experiments.
Then I will draw conclusions.
I will close this issue later.

**Comment by Mr-Precise** [comment]
It didn't work
.git directory 520 megabytes...
Copying the repository takes a long time on low performance devices like raspberry pi.
Git is good, but when there aren't too many changes in history.

**Comment by lextm** [comment]
@Mr-Precise Like I commented earlier, you don't need the entire repo to be cloned,

https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

Besides, running an IDE on Raspberry PI might be a cool idea but in reality no one is going to spend any time supporting such a setup.
