### ISSUE TITLE
Request access.

### ISSUE THREAD

**Issue by gluckez** [dotdevelop/dotdevelop#105]
@lytico @knocte 
Is it possible to add myself and @hwthomas to the members, so we can make some changes
to the repo?
This would be limited to updating the policies to set the develop branch as the main working branch,
creating a roadmap, and merging pull requests.

code changes would still be done on our own fork.

**Comment by hwthomas** [comment]
I already have write access to the `dotdevelop` repo, but @Molytho has a useful [PR](https://github.com/dotdevelop/mono-addins/pull/2) on the `mono-addins` fork, which it would be good to merge once @gluckez and I have fully reviewed it.  In time, there may be other repos in the `dotdevelop` group that need updating, but we can request write access for those if and when the time comes.

**Comment by knuxbbs** [comment]
Done. Sorry for the late response.

**Comment by gluckez** [comment]
No problem, thanks @knuxbbs!
