### ISSUE TITLE
Unable to build (myget errors)

### ISSUE THREAD

**Issue by Maniues** [dotdevelop/dotdevelop#110]
Machine: Ubuntu 20.04.
Error log:

> /home/ubuntu/dotdevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj(55,3): warning : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json.
> /home/ubuntu/dotdevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj(55,3): warning : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json.
> /home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj(29,3): error MSB4019: The imported project "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" was not found. Confirm that the expression in the Import declaration "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" is correct, and that the file exists on disk.
> /home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj(37,3): error MSB4019: The imported project "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" was not found. Confirm that the expression in the Import declaration "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" is correct, and that the file exists on disk.
> /home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj(50,3): error MSB4019: The imported project "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" was not found. Confirm that the expression in the Import declaration "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" is correct, and that the file exists on disk.
> /home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj(77,3): error MSB4019: The imported project "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" was not found. Confirm that the expression in the Import declaration "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" is correct, and that the file exists on disk.
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(303,5): warning MSB4181: The "MSBuild" task returned false but did not log an error. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(315,5): warning : Skipping restore for project '/home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj'. The project file may be invalid or missing targets required for restore. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(315,5): warning : Skipping restore for project '/home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj'. The project file may be invalid or missing targets required for restore. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(315,5): warning : Skipping restore for project '/home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj'. The project file may be invalid or missing targets required for restore. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(315,5): warning : Skipping restore for project '/home/ubuntu/dotdevelop/main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj'. The project file may be invalid or missing targets required for restore. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB3202: The project file "/home/ubuntu/dotdevelop/main/external/xwt/Xwt.Gtk/Xwt.Gtk.csproj" was not found. [/home/ubuntu/dotdevelop/main/src/addins/MacPlatform/MacPlatform.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB4181: The "MSBuild" task returned false but did not log an error. [/home/ubuntu/dotdevelop/main/src/addins/MacPlatform/MacPlatform.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB3202: The project file "/home/ubuntu/dotdevelop/main/external/xwt/Xwt.Gtk/Xwt.Gtk.csproj" was not found. [/home/ubuntu/dotdevelop/main/external/xwt/Xwt.Gtk.Windows/Xwt.Gtk.Windows.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB4181: The "MSBuild" task returned false but did not log an error. [/home/ubuntu/dotdevelop/main/external/xwt/Xwt.Gtk.Windows/Xwt.Gtk.Windows.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB3202: The project file "/home/ubuntu/dotdevelop/main/external/vs-editor-api/src/Editor/Text/Def/TextUiCommon/TextUICommon.csproj" was not found. [/home/ubuntu/dotdevelop/main/external/vs-editor-api/src/Editor/Text/Def/TextUICocoa/TextUICocoa.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1071,5): warning MSB4181: The "MSBuild" task returned false but did not log an error. [/home/ubuntu/dotdevelop/main/external/vs-editor-api/src/Editor/Text/Def/TextUICocoa/TextUICocoa.csproj]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1164,5): warning MSB3202: The project file "/home/ubuntu/dotdevelop/main/external/xwt/Xwt.Gtk/Xwt.Gtk.csproj" was not found. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> /tmp/NuGetScratch/cr6i7js3.7pe.nugetrestore.targets(1164,5): warning MSB4181: The "MSBuild" task returned false but did not log an error. [/tmp/NuGetScratch/scp49vmn.8ko.nugetinputs.targets]
> 

I think not working roslyn urls may be a problem or one of problems.

**Comment by Molytho** [comment]
Which branch are you building?

**Comment by Molytho** [comment]
That's strange. main builds fine on my Ubuntu. 

> /MonoDevelop.FSharp.Shared.fsproj(37,3): error MSB4019: The imported project "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" was not found. Confirm that the expression in the Import declaration "/usr/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/FSharp/Microsoft.FSharp.Targets" is correct, and that the file exists on disk.
This looks suspicious. Do you have fsharp package installed?

**Comment by Maniues** [comment]
I'm just trying again using [building instructions](https://github.com/dotdevelop/dotdevelop/blob/main/Building.md) on a new fresh Ubuntu 20 image. I'll check it again.

**Comment by Maniues** [comment]
I got one error about FSharp. I'm sure it's installed on my computer.

```
Paket failed with
-> Could not download FSharp.Compiler.Service 31.0.
-> Couldn't get package details for package FSharp.Compiler.Service 31.0 on https://api.nuget.org/v3/index.json.
-> All p - 2_https://nuget.org/api/v2/Packages?$filter=(tolower(Id) eq 'fsharp.compiler.service') and (Version eq '31.0.0') '31.0.0')
```

**Comment by Maniues** [comment]
Closing this issue, cause I finally built DotDevelop. Maybe temporary Internet connection issue. I don't know.
