### ISSUE TITLE
CI Pipeline fails because of a lost package

### ISSUE THREAD

**Issue by gluckez** [dotdevelop/dotdevelop#112]
The package in question is this one:
Microsoft.VisualStudio.CodingConventions

I was looking into creating a new pipe for a GTK3 upgrade, when I noticed all pipes were failing
because nuget couldn't find a specific version of that package. I'm not sure why, I can't find it anywhere
either. but locally it seemed that nuget has an older version available: 1.1.20180503.2
Ideally, this old package should be factored out and replaced by something newer, so maybe it's smth
to put on the roadmap.

**Comment by lucas-04** [comment]
Is it possible to compile at the moment? The CI Pipeline is failing.

[Uploading dotdevelop-make.log…]()

In the build log I sent above, it shows this error with one package over and over again
NU1102: Unable to find package Microsoft.VisualStudio.CodingConventions with version (>= 1.1.20191022.5)

**Comment by gluckez** [comment]
@lucas-04 unfortunately, no.
I have a working version on my own fork, but am reluctant to merge that at the moment
because it is a preparation of porting dotDevelop to GTK3.
But doing that is something that I can't do alone, so I'm afraid more work is needed before
I can create a pull request.

**Comment by malix0** [comment]
Hi, I check my VisualStudio 2022 installation and I found Microsoft.VisualStudio.CodingConventions.dll version 1.1.2301.171 this dll is really small.

IMHO according to this article [Visual Studio IntelliCode now infers coding conventions for consistent code](https://devblogs.microsoft.com/visualstudio/visual-studio-intellicode-inferring-coding-conventions-for-consistent-code/) looks Microsoft.VisualStudio.CodingConventions is just a wrapper around IntelliCode?

**Comment by gluckez** [comment]
@malix0 even though it's possible that that library is distributed with visual studio as a dll, it's unwise to include it in dotdevelop for several reasons.
It's a dll, we don't have a clear view on it's own dependencies, and we would need to write a wrapper to import it. The aim is to move away from windows specific libraries and the mono/net framework dependency. So, while It's now downgraded to a previous version, it should be replaced in the future.
In my personal opinion, we should also not strive to have coding conventions dictated by microsoft, even if I do follow those conventions myself.

**Comment by MakiWolf** [comment]
> Hi, I check my VisualStudio 2022 installation and I found Microsoft.VisualStudio.CodingConventions.dll version 1.1.2301.171 this dll is really small.

For interesting. Does this dll exist on windows or mac or on both operating systems? Becuase Visual Studio for Mac was build on top of MonoDevelop a long time ago.

**Comment by lextm** [comment]
> Does this dll exist on windows or mac or on both operating systems?

No, it doesn't. Strictly such assemblies are part of VS, so MonoDevelop cannot depend on them.

**Comment by MakiWolf** [comment]
The package is often included in code, so it will be difficult to replace or remove. Hopefully we find a solution for that problem.
Search results for Microsoft.VisualStudio.CodingConventions
https://github.com/search?q=repo%3Adotdevelop%2Fdotdevelop%20Microsoft.VisualStudio.CodingConventions&type=code
Search results for ICodingConventionContext
https://github.com/search?q=repo%3Adotdevelop%2Fdotdevelop+ICodingConventionContext&type=code
