### ISSUE TITLE
Merge Microsoft.VisualStudio.Text.Editor.Implementation.CrossPlatform

### ISSUE THREAD

**Issue by knuxbbs** [dotdevelop/dotdevelop#15]
Merge https://github.com/mkrueger/Microsoft.VisualStudio.Text.Editor.Implementation.CrossPlatform with `dotdevelop/main/external/vs-editor-api`.

**Comment by lytico** [comment]
our repo is here:
https://github.com/dotdevelop/Microsoft.VisualStudio.Text.Editor.Implementation.CrossPlatform

**Comment by lytico** [comment]
its a stub, not usefull
