### ISSUE TITLE
netcoredbg

### ISSUE THREAD

**Issue by lytico** [dotdevelop/dotdevelop#19]
do we need it?

are legal problems?:
https://github.com/dotnet/core/issues/505

alternative
https://github.com/Samsung/netcoredbg

**Comment by scherenhaenden** [comment]
Hi, 
the samsung debugger does not work. 
I think that MS is trying to kill mono at any cost. That debugger ain't gonna work on linux I think. 

I'm very naive on this question but I need to do it. How viable is to just reuse the old compiler and just make it work better and compatible with the new versions of .net and also with dotnetcore?

**Comment by lytico** [comment]
they are working on it:
https://github.com/redhat-developer/netcoredbg-theia-plugin

**Comment by lextm** [comment]
The samsung debugger repo has been active again in the past few months and the progress seems promising.

Since now this fork contains every bits needed to build MonoDevelop for Linux, I think it might be possible to merge [my extension](https://github.com/lextudio/monodevelop.netcoredbg) with this repo directly, so new users no longer need to install that separately.

**Comment by lytico** [comment]
I'll test it as soon as possible, and, if working, add it to recent dotdevelop-sources.

**Comment by lytico** [comment]
tested and works so lala. i'v integrated it into branch https://github.com/dotdevelop/dotdevelop/commits/dotdevelop_oe_8.2.6
@lextm : many thanks!

**Comment by scherenhaenden** [comment]
wow... are you guys still working on this project? it could be great if one day it actually works

**Comment by lytico** [comment]
with https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.6, it works fine.

currently netcoredebug is not in the build process, you need to build it manually:
```
cd main/external/Samsung.Netcoredbg
bash build.sh
```
then it's in 

`main/build/AddIns/Samsung.Netcoredbg`

**Comment by lytico** [comment]
follow up: #47
