### ISSUE TITLE
[Subprojects] change git-submodules to dotdevelop ones

### ISSUE THREAD

**Issue by lytico** [dotdevelop/dotdevelop#2]
/.gitmodules

**Comment by lytico** [comment]
done:

[submodule "main/external/xwt"]
	path = main/external/xwt
	url = git://github.com/dotdevelop/xwt
	branch = dotdevelop

[submodule "main/external/vs-editor-api"]
	path = main/external/vs-editor-api
	url = https://github.com/dotdevelop/vs-editor-api.git
	branch = dotdevelop

**Comment by knuxbbs** [comment]
Done.
