### ISSUE TITLE
Is the project still in the works ?

### ISSUE THREAD

**Issue by SeleDreams** [dotdevelop/dotdevelop#24]
I was wondering if the project is still in progress as I haven't really seen any progress in a while

**Comment by FlaviusHouk** [comment]
Only few guys are discussing what exactly will be done with this fork. People cannot start to work together without understanding what are they doing. Someone has some achievements but without proper coordinations and enthusiasm there will be no further progress.

I hope this work will continue, but now there isn't much.

**Comment by lytico** [comment]
mostly to try to get something working in forks of users

take a look here:

https://github.com/dotdevelop/dotdevelop/network

**Comment by lytico** [comment]
see current working version:
https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.1.5
