### ISSUE TITLE
Consider migration to GitLab

### ISSUE THREAD

**Issue by hardhub** [dotdevelop/dotdevelop#25]
Hi,

I have to said that github is not reliable anymore.

My account in mono repos is disabled without any notice and without a reason.

Maybe it is because I wrote about EEE in this issue: https://github.com/mono/monodevelop/issues/8006   
But in reality I do not know why...

Since MS owns github, developing anything in alternative to MS can be a problem on their platform.

So at least take this information into consideration because it can be really important.

**Comment by lytico** [comment]
can you specify more concrete what means:

"My account in mono repos is disabled"

what repos?

**Comment by hardhub** [comment]
> 
> 
> can you specify more concrete what means:
> 
> "My account in mono repos is disabled"
> 
> what repos?

All repos at /mono/[anything]
