### ISSUE TITLE
MonoDevelop.VersionControl.Git fails to compile

### ISSUE THREAD

**Issue by lytico** [dotdevelop/dotdevelop#30]
MonoDevelop.VersionControl.Git fails to compile on some distries, eg. plain Ubuntu 20.04, but compiles on some production machines 

see discussion before: https://github.com/dotdevelop/dotdevelop/pull/28

**Comment by lytico** [comment]
the build process is quite complicated, goes over 4 git-repos.

it tries to compile

https://github.com/dotdevelop/dotdevelop/blob/7603eda263d00230297b8188a1a4cf617d540c02/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj#L148-L150

with this batch, using a git-sha:

https://github.com/dotdevelop/dotdevelop/blob/7603eda263d00230297b8188a1a4cf617d540c02/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/build_libgit2.sh#L3-L11

AND it depends on 

https://github.com/dotdevelop/dotdevelop/blob/7603eda263d00230297b8188a1a4cf617d540c02/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj#L96

lets look at it, its in another repo:

**Comment by lytico** [comment]
and starts to build this proj.  I guess the critical parts are here:

https://github.com/dotdevelop/libgit2sharp/blob/99c056d88c75c858e47d58a0eea6d0af982fe25d/LibGit2Sharp/LibGit2Sharp.csproj#L42-L43

here it generates a part of code, depending on the commit-id of ...

https://github.com/dotdevelop/libgit2sharp/blob/99c056d88c75c858e47d58a0eea6d0af982fe25d/Targets/CodeGenerator.targets#L17-L28

**Comment by lytico** [comment]
ok, we're not alone:
https://github.com/dotnet/Nerdbank.GitVersioning/issues/491

**Comment by hwthomas** [comment]
that's useful to know, at least.  The build process does seem very complex however (and I'm in awe at your analysis above).  I wonder how necessary this complexity is - the last commits on mono/libgit2sharp were 6 yrs ago, so it seems to be pretty stable...
It also seems that there might be a similar circularity with glade-sharp2.  It's needed to build stetic, but it's not part of gtk-sharp, and the only place I could find it was in MonoDevelop 7.8.4 (the last release from monodevelop.com), which is where I copied it from...
I've got libgit2 v1:1.10-1 installed on my main Arch PC, but installing this in the clean Manjaro (or Mint) VM doesn't help things, so it's not that that is getting it to build with 0 errors.

**Comment by lytico** [comment]
i tried this, a little bit better:

in LibGit2Sharp.csproj using the latest nerdbank:

```
<PackageReference Include="Nerdbank.GitVersioning" Version="3.4.161-alpha">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```
getting

```
"/home/user/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj" (Standardziel) (144) ->
"/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets" (GetBuildVersion_Properties Ziel) (145) ->
(GetBuildVersionCore Ziel) -> 
  /home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: Unerwarteter Fehler bei der Nerdbank.GitVersioning.Tasks.GetBuildVersion-Aufgabe.
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.ArgumentException: No git repo found here.
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: Parameter name: workingDirectory
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor (System.String workingDirectory, System.String dotGitPath, System.String committish) [0x00012] in <285e105c8c844be18548bb41b3502b3e>:0 
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at Nerdbank.GitVersioning.GitContext.Create (System.String path, System.String committish, System.Boolean writable) [0x00011] in <285e105c8c844be18548bb41b3502b3e>:0 
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner () [0x0011e] in <d261121dede14f46a78a79df800650d1>:0 
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at MSBuildExtensionTask.ContextAwareTask.Execute () [0x0005e] in <d261121dede14f46a78a79df800650d1>:0 
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <17ac7020b8724cc3ab2118010c2e573d>:0 
/home/user/.nuget/packages/nerdbank.gitversioning/3.4.161-alpha/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <17ac7020b8724cc3ab2118010c2e573d>:0 
```

**Comment by lytico** [comment]
a compiling (but not working) solution is here:
https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.4.3.12_tryfixVersionControlGit
but it crashes when opening a project unter git control

**Comment by hwthomas** [comment]
My last comment was misleading, re work on libgit2 and libgit2sharp.  The last commits on https://github/mono/libgit2 are indeed 6yrs old, but there is very recent work going on at https://github/libgit2/libgit2 and https://github/libgit2/libgit2sharp.  My apologies.

**Comment by lytico** [comment]
on https://github.com/mono/libgit2sharp/commits/main, they work hard ... this is the branch they use.
and latest commit in the branch used in mono/monodevelop is 1 year: https://github.com/mono/libgit2/commits/vs-8.0-v0.26.8

**Comment by lextm** [comment]
Is it possible to remove Git integration at this moment? I prefer the following,

* A working CI pipeline
* A branch that can compile successfully on major Linux distributions

Both can set a solid ground for future community contributions, and people can move on to,

* Create packages for Linux distributions
* Work on other bug fixes or new features
* Further clean up the code base for .NET 5/6 adoption

**Comment by lytico** [comment]
yes, I'll make a branch <branch_we_work_on>_NoGit with your pull request https://github.com/dotdevelop/dotdevelop/pull/28

**Comment by lytico** [comment]
i have at least a compiling version here:

https://github.com/dotdevelop/libgit2sharp/actions/runs/460178345

and a package created with this action:

https://github.com/dotdevelop/libgit2sharp/releases/tag/dotdevelop.0.27.0-preview-g5335a181ca

so the next step is to integrate this package & kickout all libgit2sharp-stuff.

the dll's / so's / dynlibs are in this package:

LibGit2Sharp.NativeBinaries

so no need to generate them in MD

**Comment by lextm** [comment]
@lytico If the goal is to switch to NuGet package dependency, then why not choose a close enough version from NuGet.org? https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/

> No need to be on 2.x, as that might have too many breaking changes.

**Comment by lytico** [comment]
LibGit2Sharp for monodevelop is a special one, they have their own tree, and not published as NuGet package, as far as i found (not). 
I tried already using one of the Nuget-LibGit2Sharp-Packages (see comment above) in branch https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.4.3.12_tryfixVersionControlGit  :

https://github.com/dotdevelop/dotdevelop/blob/bba6c11a9d60412e83753f05209333244f96c55e/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj#L28

it's not working.

LibGit2Sharp.NativeBinaries maybe works from nuget, i'll try it soon

**Comment by lytico** [comment]
seems to work now with this branch/build:

https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.6_Gkt3

https://github.com/dotdevelop/dotdevelop/actions/runs/461801228

**Comment by knocte** [comment]
It's a bit confusing to know what's the last commit in this repo, why use new branches all the time?

How about using `main` from now on? (this way, if one wants to still check out what was the latest monodevelop commit, they can find `master` instead)

**Comment by hwthomas** [comment]
Doesn't build for me under Arch or Mint:-  
 
"Restoring packages for /home/hwt/build/dotdevelop_oe_8.6_Gkt3/main/external/Monodevelop.Netcoredbg/MonoDevelop.Debugger.DotNetCore/MonoDevelop.Debugger.DotNetCore.csproj...
The local source '/home/hwt/build/dotdevelop_oe_8.6_Gkt3/.localcache/local-feed' doesn't exist."

I'm also a bit confused - is this still part of the LibGit2Sharp issue, or some different work on Gtk3 (Gkt3?!).  And is any further development intended on the 8.1 - 8.4 branches, or does a successful 8.6 branch supercede all previous work?

**Comment by lytico** [comment]
sorry sorry sorry i closed this issue too hasty.

@knocte @hwthomas @lextm

**Comment by lytico** [comment]
@knocte @hwthomas @lextm 
about **dotdevelop_oe_8.6_Gkt3**: 
its a work issue branch (switching to gtk3) 
BUT in the process of working on it i found some bugs and resolved it
and later i found a way to switch between GTK2 / GTK3 - development
and later i removed this bug #30, still working in branch dotdevelop_oe_8.6_Gkt3

so what i have to do (and didn't) is to merge this into dotdevelop_oe_8.6.

why? i am not happy with the solution as of the build process:
the solution  - why it solves this bug - is kicking out LibGit2Sharp.proj in Main.sln and use a monodevelop-specific package (see: https://github.com/dotdevelop/libgit2sharp/releases/tag/dotdevelop.0.27.0-preview-g5335a181ca)
this script
https://github.com/dotdevelop/dotdevelop/blob/dotdevelop_oe_8.6_Gkt3/fillLocal.sh
has to be called before make or, better, to be integrated in the make - file.
Currently it's called in the workflow directly:
https://github.com/dotdevelop/dotdevelop/blob/f6fd731886a8757902a35e050f39dd17461193d6/.github/workflows/monodevelop.yml#L26

what does it do? In short, it creates a local NuGet-PackageSource (.localcache/local-feed), downloads dotdevelop.0.27.0-preview-g5335a181ca.nupkg  and add it into.

a suggestion is to make this on more sub-projects (see: #38)

so, if build integration is solved, branch dotdevelop_oe_8.6_Gkt3 is the best working branch (at the moment) and should merged into dotdevelop_oe_8.6.

i'll keep working on dotdevelop_oe_8.6_Gkt3 to try out/refactoring for switching to Gkt3

**Comment by lytico** [comment]
@hwthomas on local build, you have to run fillLocal.sh before make.

**Comment by knocte** [comment]
> @knocte I disagree that work on issues to be put on main/master directly. They should sit on their own branches and then 
> only merged via pull requests (though dotdevelop_oe_8.6_Gkt3 is definitely not a good name).

I will not be the one disagreeing with working on features in branches. But if instead of dotdevelop_oe_8.6_Gkt3 it had been named something like `GitPluginCompilationFix`, and created on the developer's fork (instead of this repo), and afterwards offered to be merged into `main` via a PullRequest, wouldn't it be less confusing?

**Comment by vmcbaptista** [comment]
IMHO, if the branch is named like @knocte suggested and all the old remote branches are removed, so that we can have just `main`, `feature` and possibly `release` branches, then we don't need developer's forks.
Currently, it is very hard for a newcomer to understand all these branches. Also, we lack some sort of backlog to understand what are the next steps and in what we can contribute.

**Comment by lytico** [comment]
i suggest to discuss branching / forking / pull request management in a new issue: #41

**Comment by lytico** [comment]
> @vmcbaptista sort of backlog to understand what are the next steps 
current discussion is here: #33

**Comment by lytico** [comment]
better solution:
replace https://github.com/dotdevelop/dotdevelop/blob/dotdevelop_oe_8.6_Gkt3/fillLocal.sh
with suggestion of
> @vmcbaptista publish NuGet packages into a GitHub Package feed
see: #38

**Comment by vmcbaptista** [comment]
Another suggestion regarding dependency to LibGit2Sharp. I understand that we can't directly depend on the latest version because we need some new types introduced by mono team. But, from what I understand the branch `dotdevelop` is far both from `main` branch of mono and also from `master` branch of original LibGit2Sharp.
I think we should try to either fork original LibGit2Sharp and introduce the necessary changes, or at least branch from mono's `main`. The goal is to be as much close as possible to the latest changes of LibGit2Sharp and have all the fixes introduced.

**Comment by lytico** [comment]
> the branch `dotdevelop` is far both from `main` branch of mono
no, there are just a few differences from  `dotdevelop_tryBuild`  to `main` branch of mono

**Comment by vmcbaptista** [comment]
> > the branch `dotdevelop` is far both from `main` branch of mono
> 
> no, there are just a few differences from `dotdevelop_tryBuild` to `main` branch of mono

ok, then I misunderstood it, please ignore my comment :)

**Comment by lytico** [comment]
as of #46, i introduced a .nugetfallback - folder to hold unlisted packages. so, https://github.com/dotdevelop/libgit2sharp/releases/tag/dotdevelop.0.27.0-preview-g5335a181ca should be added there and fillLocal.sh can be removed

**Comment by vmcbaptista** [comment]
> as of #46, i introduced a .nugetfallback - folder to hold unlisted packages. so, https://github.com/dotdevelop/libgit2sharp/releases/tag/dotdevelop.0.27.0-preview-g5335a181ca should be added there and fillLocal.sh can be removed

I argued about github packages under #38, but looks like you got an interesting alternative, I didn't know about this .nugetfallback :)

**Comment by lytico** [comment]
try to close it again, compiles:
https://github.com/dotdevelop/dotdevelop/actions/runs/483105233
in tree
https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.6
