### ISSUE TITLE
Replacement of API Cocoa?

### ISSUE THREAD

**Issue by Adahel** [dotdevelop/dotdevelop#43]
> First task is to get it to compile again without closed-source dependencies, as eveything is cluttered with Cocoa... [roadmap.md#L5](https://github.com/dotdevelop/community/blame/master/roadmap.md#L5)

Funny, I swear I didn't understand ↑.

* Facts:

  ~~**1°** GTK on Mac depends on Cocoa API. [Integration](https://wiki.gnome.org/Projects/GTK/OSX/Integration)~~ 

  **2°** XWT.GTK.Mac depends on Xamarin.Mac. [Xwt.Gtk.Mac.csproj#L50](https://github.com/dotdevelop/xwt/blob/dotdevelop/Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj#L50)

  **3°** MonoDevelop.Ide on Mac depends on Xamarin.Mac. [MonoDevelop.Ide.csproj#L45](https://github.com/dotdevelop/dotdevelop/blob/dotdevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj#L45)

  **4°** Xamarin.Mac is open source compatible with LGPLv2.1. (MIT) [LICENSE](https://github.com/xamarin/xamarin-macios/blob/main/LICENSE)

  **5°** Xamarin.Mac depends on Cocoa API, which is closed source, with some open source components. [Cocoa (API)](https://en.wikipedia.org/wiki/Cocoa_(API))

  **6°** The only open source implementation of Cocoa API that has not been abandoned and runs on mac is GNUstep. [Cocoa_(API)#Other_implementations](https://en.wikipedia.org/wiki/Cocoa_(API)#Other_implementations)

  **7°** The GNUstep license for library is LGPLv2.1. [COPYING.LIB](https://github.com/gnustep/libs-base/blob/master/COPYING.LIB)

  **8°** GNUstep do not have c# bindings.

* Questions:

  **1°** Is Cocoa API considered a system library?

  **2°** If the Cocoa API is considered a system library, why does the project need to be "without closed-source", since there is an exception for the system libraries?

  **3°** What does this part of the license LGPLv2.1 mean?

  * "It may happen that this requirement contradicts the license
restrictions of other proprietary libraries that do not normally
accompany the operating system.  Such a contradiction means you cannot
use both them and the Library together in an executable that you
distribute." [COPYING#L327](https://github.com/dotdevelop/dotdevelop/blob/dotdevelop/main/COPYING#L327)

  **4°** If the team decides not to use Cocoa API or GNUstep: Which library replaces the functionality of Cocoa API on mac?

  **5°** (I recommend.) The program will be re-licensed to GPL? [COPYING#L211](https://github.com/dotdevelop/dotdevelop/blob/dotdevelop/main/COPYING#L211)

  * If the program is will be re-licensed to GPL, which version v2 or v3?

_**Disclaimer**: This is not legal advice. This is my personal opinion as IT student. For legal advice you should contact a lawyer or an authorized legal expert of your jurisdiction_

**Comment by lextm** [comment]
1. macOS is probably not in the initial phase, as there are so many Linux distributions to consume most of the efforts. Most of your questions can only be discussed when there is already a stable Linux only release.
2. Why licensing under GPL when your work is not unique (tons of alternatives out there) in any way? GPL won't give you any benefits in that situation, and in the meantime restrict what dependencies you might rely on.

**Comment by lytico** [comment]
i have some progs out with combination GtkSharp/Xwt.GtkSharp, like planed with MonoDevelop .
they run on windows / maxOs with gkt3 installed, but without Xwt.Gtk.Mac or Xwt.Gtk.Windows, without problems.
i think it's ok to run monodevelop this way, without having a native cocoa (mac) or wpf (win) backend.

many thanks, @adahel , working this out! 
if you research for more inconsistencies in licenses in md modules and used libraries, very welcome!

**Comment by Adahel** [comment]
@lytico If the problem has already been solved, feel free to close it. Thanks for the clarification.
