### ISSUE TITLE
xbuild tool is deprecated and will be removed in future updates

### ISSUE THREAD

**Issue by TechComet** [dotdevelop/dotdevelop#44]
Hi,
try build dotdevelop on ubuntu 20.04

Updated build information
Release ID: 806000898
Git revision: d6fbfb79e763c2cc33a1a2e585b54df41be0a1e0
Build date: 2021-01-07 00:10:37+02
touch vcrevision
MSBuild auto-detection: using msbuild version '14.0' from '/opt/mono/lib/mono/xbuild/14.0/bin'.

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

MSBUILD: error MSBUILD0004: Too many project files specified

make[2]: *** [Makefile:999: restore-packages] Error 1
make[2]: Leaving directory '/home/techcomet/rr/dotdevelop/main'
make[1]: *** [Makefile:546: all-recursive] Error 1
make[1]: Leaving directory '/home/techcomet/rr/dotdevelop/main'
make: *** [Makefile:54: all-recursive] Error 1

**Comment by zocker-160** [comment]
I had the same issue, you have to install Mono 6.12.0 from https://www.mono-project.com/download/stable/#download-lin, which will give you a later version of msbuild.

That should solve your issue.

**Comment by TechComet** [comment]
I build mono from source
Ubuntu 64bit

**Comment by lextm** [comment]
Please refer to the CI manifest to learn how to properly configure your system before compiling the source code,

https://github.com/lextm/dotdevelop/blob/centos7/.github/workflows/monodevelop.yml

CentOS 8, and all major Ubuntu releases now pass, and CentOS 7 is still being worked on.

**Comment by TechComet** [comment]
befor install from soruce i tried install `mono-develop` package from apt-get but some problem for this i install from source

I not pro with git
but I use linux from 2007-2008 as default for my pc .. not beginner
I use ubuntu 20.04 now

sorry for my bad english

**Comment by lextm** [comment]
To compile the source code from dotdevelop repo, you should use both Mono and .NET Core SDK from Microsoft's 
Ubuntu feed (the manifest shows the steps and you can also refer to Mono and .NET Core home pages).

When I said that you are a beginner, I didn't mean that you know little about Linux. But Mono and MonoDevelop are not similar to other Linux packages, so you have to learn about them again. Sadly, not enough documentation is currently out there to lead you through.

**Comment by lytico** [comment]
for prerequisites ubuntu 20.04, see:

https://github.com/dotdevelop/dotdevelop/wiki/Linux-Mint-%28Ubuntu%29
