### ISSUE TITLE
NETCoreApp projects: some project Properties are not being evaluated

### ISSUE THREAD

**Issue by hwthomas** [dotdevelop/dotdevelop#75]
If a netcoreapp3.1 project is created (either using DotDevelop "New Project" or via `dotnet new`), the `TargetFrameworkIdentifier`, `TargetFrameworkVersion`, and `TargetFrameworkMoniker` properties are not being evaluated, and instead retain their Unevaluated values such as    `([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)'))`.  

This can be seen by opening and selecting the project in Solution Explorer, right-clicking and selecting 'Options', then clicking on 'General' to display the Target framework value.  
Alternatively, set a breakpoint at `main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs line 2077` when reading in a NETCoreApp project, and use the debugger to examine `msproject.EvaluatedProperties [126]` etc.  
  
Failure to evaluate these properties appears to be behind a number of other current problems with `netcoreapp` and `net5.0+` projects in DotDevelop.  
  
**Steps taken to debug the issue**  

When a new NETCoreApp project is created in DotDevelop, a new `MSBuildProject p` is created asynchronously (MonoDevelop.Projects.Extensions.ProjectTypeNode.cs - at line 48) and then evaluated (`p.Evaluate ();`  - at line 71).  Properties are evaluated in `EvaluateProperty` (MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs - at line 556) and if the code is traced when the property value contains the string `GetTargetFrameworkIdentifier` it eventually fails at `ResolveMember (line 1034)` when key value `GetTargetFrameworkIdenfifier` cannot be found in the `Dictionary cachedIntrinsicFunctions` retrieved from the MSBuild static class `IntrinsicFunctions` (see https://github.com/dotnet/msbuild/blob/vs16.10/src/Build/Evaluation/IntrinsicFunctions.cs)  

DotDevelop has been built with MSBuild Version 16.10, which (since version vs16.7) contains `internal static string GetTargetFrameworkIdentifier (string tfm)`, so it appears that it *should* be there.  

`main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj` has the correct HintPath for `Microsoft.Build.dll`, but perhaps an earlier version is being picked up from somewhere?

**Comment by hwthomas** [comment]
The code for `IntrinsicFunctions` (in folder `MonoDevelop.Projects.MSBuild`), and used by `MSBuildEvaluationContext` to evaluate the project properties is a local implementation of the functions in `Microsoft.Build`, but is now very much out-of-date, and many of the functions which are used to evaluate newer project properties are not implemented.   

As it is a local partial class, it is referenced preferentially during the property evaluations  (rather than the `Microsoft.Build.dll` referenced in the `csproj` file), and this cause the property evaluations to fail. 
  
Updating the code so that the Dictionary `cachedIntrinsicFunctions` is created dynamically at runtime from the current `Microsoft.Build.dll` fixes the problem, and all project properties now evaluate correctly.  This means that on the `Project=>Options` page, the `General` option correctly shows the `TargetFramework` being used, and this can now be changed and saved as expected.  

I'll submit a PR in the next day or so with this fix.

There are still errors when building NetCoreApp projects, so there is still plenty to do.

**Comment by gluckez** [comment]
@hwthomas great work, I do indeed see the option to create net5 projects, but I'm unable to save them when creating a new project. However, If I create a netcore 3.1 project md crashes, and afterwards I'm seeing a weird string when trying to select a target framework. Is this possibly a configuration issue on my side or is it still buggy?
I'm still trying to get used to the code base.

**Comment by hwthomas** [comment]
@gluckez : the *weird string* you mention is the Unevaluated property value for `TargetFrameworkIdentifier` as mentioned at the start of this issue.  PR #77 will fix this, but it has not been merged yet as there are other issues that become apparent if it is.  However, if you update your fork from the commits in my PR you should be able to change the `TargetFramework` from the General tab of the Project Options (though only `netcoreapp2.1` and `netcoreapp3.1` can be saved).  Dealing with `net5.0` and later requires Issue #79 to be fixed.

**Comment by gluckez** [comment]
@hwthomas I see. Lot's of work to be done. I'll pull in your commits and see what comes up. Also been tinkering with the funcloader, and that seems to work on my end. So I'll push that on a branch and see what the impact could be to update the nuget binaries, maybe I can help out.
