### ISSUE TITLE
Build: project.assets.json gets a wrong TargetFrameworkMoniker for net5 and higher

### ISSUE THREAD

**Issue by lytico** [dotdevelop/dotdevelop#79]
the TargetFrameworkMoniker ( i hope it's the right term)
written to project.assets.json is wrong for net5 and higher:

MD writes
```
 "targets": {
    ".NETFramework,Version=v5.0": {}
  }
```

rather than as
```
"targets": {
    "net5.0": {}
  }
```

**Comment by lytico** [comment]
hints

seems that it is build / parsed in this class:
main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFrameworkMoniker.cs

**Comment by lytico** [comment]
@hwthomas seems that you had this file already under suspect.

another canditate could be all this Resolver-stuff. if it's copying the wrong msbuild or nuget, then net5 ff is out

https://github.com/dotdevelop/dotdevelop/blob//6d6f43c111b3e9d9c8aab6c080c79cb82be1dd6a//main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.MSBuildResolver/Resolver.cs

**Comment by hwthomas** [comment]
In `MonoDevelop.ProjectManagement/DotNetCoreNuGetProject.cs`, line 88 onwards, a `NuGet.Framework` is set up, initially  parsing the DotNetFramework name.  Doing some tests using `NuGet.Frameworks`, results change depending on which version of `NuGet.Frameworks` is used.  Currently, DotDevelop is built with release-5.4.0, and the statement  

 `targetFramework = NuGetFramework.Parse ("net5.0");` returns  a result of `".NETFramework, Version=v5.0"`

which is what is written to the `project.assets.json` file above.  
release-5.6.0 returns `"NETCoreApp, Version=v5.0"`, whereas  
release 5.8.0 returns `"net5.0"`.    
 
Parsing "net6.0" is not done correctly until release-5.10.0 onwards.

However, trying to build DotDevelop using the release-5.10.0 versions of the nuget binaries (main/external/nuget-binary) starts to throw up a lot of errors, as the NuGet interface changes between releases.  
This looks like the correct area of the code to look at, but getting familiar with it might take some time.

**Comment by pracplayopen** [comment]
have a question that reflects perhaps too simple of a view-

why build projects.assets.json at all, since it's built by nuget restore / dotnet restore?

wouldn't it be faster and less error prone to simply let those external tools generate this file?

**Comment by hwthomas** [comment]
I couldn't agree more!  However, what *might* once have been a clean interface between the MonoDevelop GUI (which I still like) and all the external tools (msbuild, nuget, git, nunit etc) has deteriorated over the years, and is probably now unmaintainable. Building a new IDE from scratch is very appealing, but a working version of DotDevelop for .net5ff would still be a big help.

**Comment by pracplayopen** [comment]
building an ide from scratch sounds like an impedance mismatch.
hopefully there is a middle ground.

what is the smallest code to bootstrap the equivalent of 'dotnet build' using the project file path as input?
if you can do that you can wire it up and only use it when target framework requires it (or like MD used to have, an option to force the build tool used)

according to this- which believe is [the build command in dotnet](https://github.com/dotnet/msbuild/tree/main/src/Build) you have to create a project and then build it:

> [public static Microsoft.Build.Construction.ProjectRootElement Create (string path);](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction.projectrootelement.create?view=msbuild-17-netcore#microsoft-build-construction-projectrootelement-create(system-string))
>[public Project (Microsoft.Build.Construction.ProjectRootElement xml);](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project.-ctor?view=msbuild-17-netcore#microsoft-build-evaluation-project-ctor(microsoft-build-construction-projectrootelement))
>[public bool Build (string target);](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project.build?view=msbuild-17-netcore#microsoft-build-evaluation-project-build(system-string))

eg:

```
var pre = Microsoft.Build.Construction.ProjectRootElement.Create("project-or-solution-file")
var proj = new Project(pre);
proj.Build("Release");
```

not sure if this is exactly equivalent to cli when 'dotnet build' is run, but it looks close no?
