### ISSUE TITLE
netstandard2.0/2.1 projects don't build

### ISSUE THREAD

**Issue by hwthomas** [dotdevelop/dotdevelop#86]
With dotnet-sdk-2.1, dotnet-sdk-3.1 and dotnet-sdk-5.0 installed, the simplest netstandard2.0 or netstandard2.1 projects fail to build, with:-  

Error: .NET Core  SDK is required to build this application, and is not installed. 
Install the latest update to the .NET Core  SDK by visiting https://aka.ms/vs/mac/install-netcore  

Both netstandard2.0 and 2.1 *should* be supported with the above sdks

**Comment by gluckez** [comment]
@hwthomas any tips on where to start looking to fix that? I'll update my fork to include your commits and have a crack at it.
