### ISSUE TITLE
Unable to open .NET6 projects

### ISSUE THREAD

**Issue by BiologyTools** [dotdevelop/dotdevelop#99]
When opening .NET6 projects I get an SDK not found error despite having .NET6 installed. Other project types open and build with no errors.
Here's a screenshot with the error and output from dotnet --info
![image](https://user-images.githubusercontent.com/84872500/209993430-cd75bb90-9e39-4077-acd4-779f87673d1c.png)

**Comment by hwthomas** [comment]
Have a look at the notes at the end of the Arch Setup wiki page (https://github.com/dotdevelop/dotdevelop/wiki/Manjaro-%28Arch%29)  

It sounds like this issue.

**Comment by BiologyTools** [comment]
I'm not sure how to set the environmental property MSBuildEnableWorkloadResolver and I tried the setting the global.json to the suggested version but this seems to do nothing. How do I set the environmental variable?

**Comment by gluckez** [comment]
@BiologyTools which version are you using? @hwthomas has done a lot of amazing work for .net6.0 support, but that hasn't been merged yet, unfortunately. try building dotdevelop from his branch: [here](https://github.com/hwthomas/dotdevelop/tree/msbuild_version)

**Comment by BiologyTools** [comment]
@gluckez I'm using the latest version running on a fresh install of ubuntu on VirtualBox and followed the build instructions in Building.md. When trying to build the one from @hwthomas I get the following error when running make.
`make
PATH is /usr/local/share/dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/evolve/.dotnet/tools
.NET Core 6.0.404 installed in /usr/bin/dotnet
3.1.426 [/usr/share/dotnet/sdk]
5.0.408 [/usr/share/dotnet/sdk]
6.0.404 [/usr/share/dotnet/sdk]
make[1]: Entering directory '/home/evolve/dotdevelop/main'
Making all in external
make[2]: Entering directory '/home/evolve/dotdevelop/main/external'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/evolve/dotdevelop/main/external'
Making all in po
make[2]: Entering directory '/home/evolve/dotdevelop/main/po'
/usr/bin/mkdir -p ../build/locale/cs/LC_MESSAGES/
msgfmt 'cs.po' -o '../build/locale/cs/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/da/LC_MESSAGES/
msgfmt 'da.po' -o '../build/locale/da/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/de/LC_MESSAGES/
msgfmt 'de.po' -o '../build/locale/de/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/es/LC_MESSAGES/
msgfmt 'es.po' -o '../build/locale/es/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/fr/LC_MESSAGES/
msgfmt 'fr.po' -o '../build/locale/fr/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/ja/LC_MESSAGES/
msgfmt 'ja.po' -o '../build/locale/ja/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/pt_BR/LC_MESSAGES/
msgfmt 'pt_BR.po' -o '../build/locale/pt_BR/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/tr/LC_MESSAGES/
msgfmt 'tr.po' -o '../build/locale/tr/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/pl/LC_MESSAGES/
msgfmt 'pl.po' -o '../build/locale/pl/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/it/LC_MESSAGES/
msgfmt 'it.po' -o '../build/locale/it/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/zh_TW/LC_MESSAGES/
msgfmt 'zh_TW.po' -o '../build/locale/zh_TW/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/zh_CN/LC_MESSAGES/
msgfmt 'zh_CN.po' -o '../build/locale/zh_CN/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/ru/LC_MESSAGES/
msgfmt 'ru.po' -o '../build/locale/ru/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/sl/LC_MESSAGES/
msgfmt 'sl.po' -o '../build/locale/sl/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/ca/LC_MESSAGES/
msgfmt 'ca.po' -o '../build/locale/ca/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/gl/LC_MESSAGES/
msgfmt 'gl.po' -o '../build/locale/gl/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/pt/LC_MESSAGES/
msgfmt 'pt.po' -o '../build/locale/pt/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/sv/LC_MESSAGES/
msgfmt 'sv.po' -o '../build/locale/sv/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/nl/LC_MESSAGES/
msgfmt 'nl.po' -o '../build/locale/nl/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/id/LC_MESSAGES/
msgfmt 'id.po' -o '../build/locale/id/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/hu/LC_MESSAGES/
msgfmt 'hu.po' -o '../build/locale/hu/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/nb/LC_MESSAGES/
msgfmt 'nb.po' -o '../build/locale/nb/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/ko/LC_MESSAGES/
msgfmt 'ko.po' -o '../build/locale/ko/LC_MESSAGES/monodevelop.mo'
/usr/bin/mkdir -p ../build/locale/uk/LC_MESSAGES/
msgfmt 'uk.po' -o '../build/locale/uk/LC_MESSAGES/monodevelop.mo'
make[2]: Leaving directory '/home/evolve/dotdevelop/main/po'
Making all in theme-icons
make[2]: Entering directory '/home/evolve/dotdevelop/main/theme-icons'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/evolve/dotdevelop/main/theme-icons'
Making all in tests
make[2]: Entering directory '/home/evolve/dotdevelop/main/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/evolve/dotdevelop/main/tests'
make[2]: Entering directory '/home/evolve/dotdevelop/main'
if test -f "./buildinfo"; then cp "./buildinfo" "./build/bin/buildinfo"; else ./../scripts/configure.sh gen-buildinfo "./build/bin"; fi
/usr/bin/git failed
make[2]: *** [Makefile:1008: build/bin/buildinfo] Error 1
make[2]: Leaving directory '/home/evolve/dotdevelop/main'
make[1]: *** [Makefile:546: all-recursive] Error 1
make[1]: Leaving directory '/home/evolve/dotdevelop/main'
make: *** [Makefile:54: all-recursive] Error 1

`

**Comment by BiologyTools** [comment]
@gluckez I'm using the latest one from github dotdevelop I followed the Building.md instructions. I'm running ubuntu on VirtualBox if that matters. When I used the version from @hwthomas I got the same error message when opening .NET6 projects. I checked and the .NET Core Debugger is attached.

**Comment by hwthomas** [comment]
@BiologyTools  
> I'm not sure how to set the environmental property MSBuildEnableWorkloadResolver  

`export MSBuildEnableWorkloadResolver=false`  in a terminal, before starting dotdevelop with...  

`mono ./main/build/bin/MonoDevelop.exe --no-redirect `  

Ubuntu 20.04 (LTS) in a VM is probably the easiest way to build DotDevelop at the moment

**Comment by BiologyTools** [comment]
@hwthomas Thank you the solution you provided for MSBuildEnableWorkloadResolver worked!
